version: '3.8'

networks:
  docker-ubuntu-net:
    external: true
volumes:
  maven:
    name: maven

services:
  web:
    build: .
    container_name: cloud-container
    restart: always
    networks:
      - docker-ubuntu-net
    ports:
      - "3000:3000"
    volumes:
      - maven:/root/.m2/repository
