spring:
  application:
    name: service-oss
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 172.16.6.77:8848
        namespace: f5b2bb31-650a-4d32-8ae1-66b11500243d
      discovery:
        server-addr: 172.16.6.77:8848
        namespace: f5b2bb31-650a-4d32-8ae1-66b11500243d
  config:
    import:
      - optional:nacos:service-oss.yaml  # 监听 DEFAULT_GROUP:test.yml