# application.yml (不能是bootstrap.yml)
spring:
  application:
    name: service-gateway
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 172.16.6.77:8848
        namespace: 520c7a82-ac10-4ea5-80b0-ea1488bb6b66
      discovery:
        server-addr: 172.16.6.77:8848
        namespace: 520c7a82-ac10-4ea5-80b0-ea1488bb6b66
  config:
    import:
      - optional:nacos:service-gateway.yaml  # 监听 DEFAULT_GROUP:test.yml
service-name: service-auth


