spring:
  application:
    name: service-auth
  cloud:
    nacos:
      config:
        server-addr: 192.168.77.130:8848
        namespace: f5b2bb31-650a-4d32-8ae1-66b11500243d
      discovery:
        server-addr: 192.168.77.130:8848
        namespace: f5b2bb31-650a-4d32-8ae1-66b11500243d
    sentinel:
      transport:
        port: 8710
        dashboard: localhost:8080
  config:
    import:
      - optional:nacos:service-auth.yaml  # 监听 DEFAULT_GROUP:test.yml
knife4j:
  enable: true
time:
  token: 100000
  refresh: 200000